############################################################################
# Two secrets the server container needs, both generated by Terraform
# (never typed by a human, never hardcoded) and stored in Secrets Manager.
# ECS's task definition (ecs.tf) references these by ARN and AWS injects
# the real value into the container's environment at startup — the value
# never appears in the task definition itself, in the console, or in any
# log.
############################################################################

resource "random_password" "db_password" {
  length  = 32
  special = false # avoid characters (@ / : etc) that would need URL-encoding inside a postgresql:// connection string
}

resource "random_password" "admin_secret" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "database_url" {
  name = "loupgarou/database-url"
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  # Composed here, once, from the RDS endpoint + the random password above —
  # exactly the single connection string Prisma's DATABASE_URL expects.
  secret_string = "postgresql://${var.db_username}:${random_password.db_password.result}@${aws_db_instance.main.endpoint}/${var.db_name}?schema=public"
}

resource "aws_secretsmanager_secret" "admin_secret" {
  name = "loupgarou/admin-secret"
}

resource "aws_secretsmanager_secret_version" "admin_secret" {
  secret_id     = aws_secretsmanager_secret.admin_secret.id
  secret_string = random_password.admin_secret.result
}
