variable "aws_region" {
  description = "AWS region everything in this stack lives in."
  type        = string
  default     = "eu-west-3" # Paris
}

variable "vpc_cidr" {
  description = "CIDR block for the whole VPC. /16 gives 65,536 addresses — far more than this project needs, but it's the conventional size and costs nothing to over-allocate."
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "Number of availability zones to spread subnets across. 2 is the minimum AWS requires for an ALB, and plenty for a project this size."
  type        = number
  default     = 2
}

variable "db_name" {
  description = "Name of the initial Postgres database created inside the RDS instance."
  type        = string
  default     = "loupgarou"
}

variable "db_username" {
  description = "Master username for the RDS instance. There is deliberately no db_password variable — the password itself is auto-generated by RDS and stored in Secrets Manager, never typed anywhere (see manage_master_user_password in rds.tf)."
  type        = string
  default     = "loupgarou_admin"
}

variable "domain_name" {
  description = "The registered domain, without any subdomain (apex). Must already exist as a Route53 hosted zone in THIS AWS account — deliberately has no default (unlike most variables here) so nobody reusing this repo accidentally deploys pointing at someone else's domain. Must be set explicitly via terraform.tfvars or -var."
  type        = string
}

variable "github_repository" {
  description = "Your GitHub repo as \"owner/repo\" (e.g. \"fouzi/loupgarou\"). Used to restrict which repo's GitHub Actions runs are allowed to assume the CI IAM roles below — deliberately has no default, so this must be set explicitly (via terraform.tfvars or -var) rather than silently trusting a placeholder."
  type        = string
}
