variable "aws_region" {
  description = "AWS region everything in this stack lives in."
  type        = string
  default     = "eu-west-3" # Paris
}

variable "vpc_cidr" {
  description = "CIDR block for the whole VPC. /16 gives 65,536 addresses — far more than this project needs, but it's the conventional size and costs nothing to over-allocate."
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "Number of availability zones to spread subnets across. 2 is the minimum AWS requires for an ALB, and plenty for a project this size."
  type        = number
  default     = 2
}

variable "db_name" {
  description = "Name of the initial Postgres database created inside the RDS instance."
  type        = string
  default     = "loupgarou"
}

variable "db_username" {
  description = "Master username for the RDS instance. There is deliberately no db_password variable — the password itself is auto-generated by RDS and stored in Secrets Manager, never typed anywhere (see manage_master_user_password in rds.tf)."
  type        = string
  default     = "loupgarou_admin"
}
